version: '3.1'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    depends_on:
      - mysql

  mysql:
   image: mysql
   restart: always
   container_name: db-mysql
   ports:
    - 3306:3306
   environment:
     MYSQL_DATABASE: codingchallenge
     MYSQL_ROOT_PASSWORD: root
     MYSQL_ROOT_USER: root
     MYSQL_USER: testuser
     MYSQL_PASSWORD: testpassword
   volumes:
    - ./dump:/docker-entrypoint-initdb.d